server:
  port: 8888


spring:
  application:
    name: cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wangchuangjava/spring-cloud.git
          search-paths: /spring-cloud/git-config
          username: wangchuangjob@163.com
          password: wzx997322



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/